### ISSUE TITLE
请教用法

### ISSUE THREAD

**Issue by HaveF** [gavinning/deploy#1]
没翻源码，只是看了下说明，没有看太懂啊

应用场景是？
服务器上写一个`deploy.js`文件，配置写到里面，然后每次代码写完之后，ssh到服务器上，然后运行一下这个deploy.js文件？

如果是这种用法，那写个deploy的script，放在package.json里面不就可以了？

```
"scripts":{
 "deploy":"git pull && npm install && pm2 start index.js"
}
```

**Comment by gavinning** [comment]
如果是单纯部署可以的，我当时是想写一个配有前端webUI界面的小型项目部署系统平台，可以部署项目，记录发布历史，允许回滚等一些常用操作，当时只写了底层就去忙别的了，忙完别的也忘了这事了。。。

**Comment by HaveF** [comment]
哈哈:sweat_smile:，好吧
